version: "2"
services:
  nginx:
    extends:
      file: base.yml
      service: nginx
    links:
      - app

  postgres:
    extends:
      file: base.yml
      service: postgres

  redis:
    extends:
      file: base.yml
      service: redis

  app:
    extends:
      file: base.yml
      service: app
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - redis
      - postgres

  worker:
    extends:
      file: base.yml
      service: worker
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - redis
      - postgres

  beat:
    extends:
      file: base.yml
      service: beat
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - redis
      - postgres

