version: "2"
services:
  nginx:
    extends:
      file: base.yml
      service: nginx
    links:
      - app
    ports:
      - "3002:80"

  app:
    extends:
      file: base.yml
      service: app
    build:
      args:
        - DJANGO_ENV=prod
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis

  worker:
    extends:
      file: base.yml
      service: worker
    build:
      args:
        - DJANGO_ENV=prod
    links:
      - redis
      - postgres
    depends_on:
      - app

  beat:
    extends:
      file: base.yml
      service: beat
    build:
      args:
        - DJANGO_ENV=prod
    depends_on:
      - worker

  postgres:
    extends:
      file: base.yml
      service: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data/

  redis:
    extends:
      file: base.yml
      service: redis
    volumes:
      - ./redis-data:/data
